# Page No. 147
library(venneuler)
library(permutations)
library(prob)
library(dplyr)
library(permute)
s<-c('g,b')
print(s)
df<-data.frame(tosscoin(2))
print(df %>% slice(1,3))
setA<-df %>% slice(1)
setB<-df %>% slice(3)
s1=as.numeric(count(setA))
s2=as.numeric(count(setB))
per <- data.frame(matrix(unlist(permn(7)), nrow=length(permn(7)), byrow=TRUE))
print(filter(per, X1==2))
perA<-filter(per, X1==4)
perB<-filter(per,X2==2)
perC<-filter(per,X1==3)
c1=as.numeric(count(perB))
c2=as.numeric(count(perC))
AunionB<-rbind(perA, perB)
print(AunionB)
res<-subset(rolldie(2),X1+X2==7)
print(res)
vd1 <- venneuler(c(A=c1, B=c2,"A&B"=100 ))
vd1$colors<-c(0.8,0.8)
plot(vd1)
vd2 <- venneuler(c(A=s1, B=s2,"A&B"=1))
plot(vd2)
vd3 <- venneuler(c(A=c1, B=c2,"A&B"=0))
plot(vd3)