# Page No. 211
library(MASS)
total_balls=66
p<-c(11,10,9,8,7,6,5,4,3,2,1)
p1=fractions(p[1]/total_balls)
print(p1)
p2=fractions(p[2]/total_balls)
print(p2)
p3=fractions(p[3]/total_balls)
print(p3)
p4=fractions(p[4]/total_balls)
print(p4)
p5=fractions(p[5]/total_balls)
print(p5)
p6=fractions(p[6]/total_balls)
print(p6)
p7=fractions(p[7]/total_balls)
print(p7)
p8=fractions(p[8]/total_balls)
print(p8)
p9=fractions(p[9]/total_balls)
print(p9)
p10=fractions(p[10]/total_balls)
print(p10)
p11=fractions(p[11]/total_balls)
print(p11)
# The answer may vary due to difference in representation